local gameDefaults = require("Scripts.gameDefaults")

local gameDetails = {
	level1  = require("Scripts.levels.level1"),   -- Ralphie the Cat: Remember your colors
	level2  = require("Scripts.levels.level2"),   -- Webster: Size and Shape
	level3  = require("Scripts.levels.level3"),   -- Oliver: bigger/smaller
	level4  = require("Scripts.levels.level4"),   -- Chip: Shape Up!
	level5  = require("Scripts.levels.level5"),   -- Pinkie: Identify Numbers
	level6  = require("Scripts.levels.level6"),   -- Percival The Puppy: Color and Shape puzzles
	level7  = require("Scripts.levels.level7"),   -- Sunshine: Review 1
	level8  = require("Scripts.levels.level8"),   -- Chauncey: Touch Counting
	level9  = require("Scripts.levels.level9"),   -- Oleg: Colors Shapes & Counting
	level10 = require("Scripts.levels.level10"),  -- Webster: In the Basket
	level11 = require("Scripts.levels.level11"),  -- Bella: How Many?
	level12 = require("Scripts.levels.level12"),  -- Cordelia: Counting Skills
	level13 = require("Scripts.levels.level13"),  -- Bella: Numeric Order
	level14 = require("Scripts.levels.level14"),  -- Chloe: What Comes Next
	level15 = require("Scripts.levels.level15"),  -- Percival Puppy: Build the Number
	level16 = require("Scripts.levels.level16"),  -- Percival: First and Last
	level17 = require("Scripts.levels.level17"),  -- Oliver: Matching Fun
	level18 = require("Scripts.levels.level18"),  -- Ralphie: Review 3
	level19 = require("Scripts.levels.level19"),  -- Dudley: Pop It
	level20 = require("Scripts.levels.level20"),  -- Sunshine Bee: Matching numbers to groups
	level21 = require("Scripts.levels.level21"),  -- Chauncey: Spot the Difference
	level22 = require("Scripts.levels.level22"),  -- Pete: Greatest and Least
	level23 = require("Scripts.levels.level23"),  -- Oliver: Matching Groups
	level24 = require("Scripts.levels.level24"),  -- Sunshine: Review 3
	level25 = require("Scripts.levels.level25"),  -- Chauncey: Building Bigger Numbers
	level26 = require("Scripts.levels.level26"),  -- Chloe: Skip Counting by 2s
	level27 = require("Scripts.levels.level27"),  -- Pete: What's Missing
	level28 = require("Scripts.levels.level28"),  -- Ralphie: Image Patterns
	level29 = require("Scripts.levels.level29"),  -- Pinkie: Skip Counting by 5s
	level30 = require("Scripts.levels.level30"),  -- Oleg: Review 4 Nimble Numbers
	level31 = require("Scripts.levels.level31"),  -- Cordelia: The Order of Things
	level32 = require("Scripts.levels.level32"),  -- Dudley: One More
	level33 = require("Scripts.levels.level33"),  -- Pinkie: Greater Than
	level34 = require("Scripts.levels.level34"),  -- Sunshine the Bee
	level35 = require("Scripts.levels.level35"),  -- Ralphie: How Many More
	level36 = require("Scripts.levels.level36"),  -- Cordelia: Review 5 Going Up
	level37 = require("Scripts.levels.level37"),  -- Oliver: Ten More
	level38 = require("Scripts.levels.level38"),  -- Webster: What's Missing 2s 5s 10s
	level39 = require("Scripts.levels.level39"),  -- Pete's Apples and Bananas
	level40 = require("Scripts.levels.level40"),  -- Percival The Puppy
	level41 = require("Scripts.levels.level41"),  -- Bella: Review 6
	level42 = require("Scripts.levels.level42"),  -- Sunshine: Which two?
	level43 = require("Scripts.levels.level43"),  -- Oliver
	level44 = require("Scripts.levels.level44"),  -- Pinkie Pig: One to Five More
	level45 = require("Scripts.levels.level45"),  -- Dudley: Addition Mix Up
	level46 = require("Scripts.levels.level46"),  -- Daisy: True or False Addition
	level47 = require("Scripts.levels.level47"),  -- Chip: Addition Word Problems
	level48 = require("Scripts.levels.level48"),  -- Chauncey: Review 7 Addition Magician
	level49 = require("Scripts.levels.level49"),  -- Chloe: Less Than
	level50 = require("Scripts.levels.level50"),  -- Percival: Take Away
	level51 = require("Scripts.levels.level51"),  -- Chloe
	level52 = require("Scripts.levels.level52"),  -- Percival The Puppy: Counting to 10
	level53 = require("Scripts.levels.level53"),  -- Ralphie: One to Five Less
	level54 = require("Scripts.levels.level54"),  -- Cordelia: Subtraction Mix Up
	level55 = require("Scripts.levels.level55"),  -- Sunshine: subtraction equations
	level56 = require("Scripts.levels.level56"),  -- Oliver: Subtraction Word Problems
	level57 = require("Scripts.levels.level57"),  -- Oleg: Action Subtraction
	level58 = require("Scripts.levels.level58"),  -- Pete the Frog: Subtraction to 5
	level59 = require("Scripts.levels.level59"),  -- Pete the Frog: Subtraction to 5
	level60 = require("Scripts.levels.level60"),  -- Pete the Frog: Subtraction to 5
	level61 = require("Scripts.levels.level61"),  -- Pete the Frog: Subtraction to 5
	level62 = require("Scripts.levels.level62"),  -- Pete the Frog: Subtraction to 5
	level63 = require("Scripts.levels.level63"),  -- Pete the Frog: Subtraction to 5
	level64 = require("Scripts.levels.level64"),  -- Pete the Frog: Subtraction to 5
	level65 = require("Scripts.levels.level65"),  -- Pete the Frog: Subtraction to 5
	level66 = require("Scripts.levels.level66"),  -- Pete the Frog: Subtraction to 5
	level67 = require("Scripts.levels.level67"),  -- Pete the Frog: Subtraction to 5
	level68 = require("Scripts.levels.level68"),  -- Pete the Frog: Subtraction to 5
	level69 = require("Scripts.levels.level69"),  -- Pete the Frog: Subtraction to 5
	level70 = require("Scripts.levels.level70"),  -- Pete the Frog: Subtraction to 5
	level71 = require("Scripts.levels.level71"),  -- Pete the Frog: Subtraction to 5
	level72 = require("Scripts.levels.level72"),  -- Pete the Frog: Subtraction to 5
	level73 = require("Scripts.levels.level73"),  -- Pete the Frog: Subtraction to 5
	level74 = require("Scripts.levels.level74"),  -- Pete the Frog: Subtraction to 5
	level75 = require("Scripts.levels.level75"),  -- Pete the Frog: Subtraction to 5
	level76 = require("Scripts.levels.level76"),  -- Pete the Frog: Subtraction to 5
}
gameDefaults.applyDefaults(gameDetails)
return gameDetails
